"""Add CorridorKey buttons to DaVinci Resolve's Workspace > Scripts menu (macOS).

    uv run python scripts/install_resolve_menu.py            # install
    uv run python scripts/install_resolve_menu.py --remove   # uninstall

Each button opens a Terminal window that runs scripts/resolve_bridge.py on the
clip under the playhead, so progress and errors stay visible and Resolve
itself is never blocked. Needs Resolve Studio with Preferences > General >
External scripting set to Local.
"""

from __future__ import annotations

import argparse
import shlex
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MENU_DIR = Path.home() / "Library/Application Support/Blackmagic Design/DaVinci Resolve/Fusion/Scripts/Utility"
VISION = "--with pyobjc-framework-Vision --with pyobjc-framework-Quartz"

BUTTONS = {
    "CorridorKey - Vision hint (person)": f"uv run --extra mlx {VISION} python scripts/resolve_bridge.py --auto-hint",
    "CorridorKey - Screen hint (chroma)": "uv run --extra mlx python scripts/resolve_bridge.py --auto-hint screen",
    "CorridorKey - Vision hint (objects)": (
        f"uv run --extra mlx {VISION} python scripts/resolve_bridge.py --auto-hint objects"
    ),
    "CorridorKey - V2 hint": "uv run --extra mlx python scripts/resolve_bridge.py",
    "CorridorKey - import result only": "uv run --extra mlx python scripts/resolve_bridge.py --import-only",
}

TEMPLATE = """# Generated by CorridorKey scripts/install_resolve_menu.py - re-run it after moving the repo.
import subprocess

COMMAND = {command!r}
quoted = COMMAND.replace("\\\\", "\\\\\\\\").replace('"', '\\\\"')
script = 'tell application "Terminal"\\n activate\\n do script "' + quoted + '"\\nend tell'
subprocess.Popen(["osascript", "-e", script])
"""


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--remove", action="store_true", help="delete the CorridorKey buttons")
    args = p.parse_args()
    if sys.platform != "darwin":
        sys.exit("The Resolve menu buttons are macOS only.")

    MENU_DIR.mkdir(parents=True, exist_ok=True)
    for name, cmd in BUTTONS.items():
        path = MENU_DIR / f"{name}.py"
        if args.remove:
            path.unlink(missing_ok=True)
            continue
        command = f"cd {shlex.quote(str(REPO))} && {cmd}"
        path.write_text(TEMPLATE.format(command=command))
        print(f"installed: {path.name}")
    print("Removed." if args.remove else f"Done. In Resolve: Workspace > Scripts > (in {MENU_DIR.name})")


if __name__ == "__main__":
    main()
